name: Android CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build and test
        run: tools/ci-build.sh

      - name: Create repository archive
        run: zip -r Aforos_v9.1_project.zip . -x "*.git*"
        working-directory: .

      - name: Upload archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: Aforos_ci.zip
          path: Aforos_v9.1_project.zip
